name: Build Chatsper for Desktop

on:
  workflow_dispatch:
  push:
    tags: 
      - v.*

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    name: "Build for ${{ matrix.os }}"
    runs-on: ${{ matrix.runson }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: windows
            goos: windows
            goarch: amd64
            ext: .exe
            runson: windows-latest
          - os: linux
            goos: linux
            goarch: amd64
            ext: ""
            runson: ubuntu-latest
          - os: macos
            goos: darwin
            goarch: amd64
            ext: ""
            runson: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: oven-sh/setup-bun@v2

      - run: cd ./Chatsper.Frontend/ && bun i && bun run build
      - run: cd ./Chatsper.Backend/internal/api/router/ && ../../../bin/rice-${{ matrix.goos }}${{ matrix.ext }} embed-go
      - name: Build
        env:
          FRONTEND_BUILD: ../Chatsper.Frontend/build
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
        run: cd ./Chatsper.Backend/ && go build -o chatsper-${{ matrix.os }}${{ matrix.ext }} ./cmd/main.go && ls

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chatsper-${{ matrix.os }}
          path: Chatsper.Backend/chatsper-${{ matrix.os }}${{ matrix.ext }}

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          
          tag_name: ${{ github.ref_name }}
          token: ${{ github.token }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          name: "Automated Release for Chatsper (Linux, Win, MacOS)"
          prerelease: false
          body: "This Release is currently only for the Chatsper-Updater! It is intendet to released. But has currently no detailed Release notes. (Currently it only release the artifects from the Action run.)"