name: Build Chatsper for Desktop
on:
  workflow_dispatch:
  push:
    branches:
      - chatsper

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: "Build for ${{ matrix.os }}"
    runs-on: ${{ matrix.runson }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: windows
            goos: windows
            goarch: amd64
            ext: .exe
            runson: windows-latest
          - os: linux
            goos: linux
            goarch: amd64
            ext: ""
            runson: ubuntu-latest
          - os: macos
            goos: darwin
            goarch: amd64
            ext: ""
            runson: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: oven-sh/setup-bun@v2

      - run: cd ./Chatsper.Frontend && bun i && bun run build
      - name: Build
        env:
          FRONTEND_BUILD: ../Chatsper.Frontend/build
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
        run: |
          cd ./Chatsper.Backend && go build -o chatsper-${{ matrix.os }}${{ matrix.ext }} ./cmd/main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chatsper-${{ matrix.os }}
          path: chatsper-${{ matrix.os }}${{ matrix.ext }}